### PR TITLE
Permanent border on focus window plugin

### PR DESCRIPTION
**Pull request by tlsomers**
A permanent border around the single focused window to satisfy issue https://github.com/workspacer/workspacer/issues/228 (and my own preference).

### CODE REVIEW

File: src/workspacer.Bar/BarPluginConfig.cs [hunk 1]
```diff
@@ -12,7 +12,6 @@ public class BarPluginConfig
 
         public Color DefaultWidgetForeground { get; set; } = Color.White;
         public Color DefaultWidgetBackground { get; set; } = Color.Black;
-        public Color Background { get; set; } = Color.Black;
```
Comment (josteink) [inline src/workspacer.Bar/BarPluginConfig.cs:15]: Any reason why this property has been removed?

File: src/workspacer.Gap/Layouts/GapLayoutEngine.cs [hunk 2]
```diff
@@ -8,23 +8,38 @@ public class GapLayoutEngine : ILayoutEngine
...
+                    {
+                        return new WindowLocation(l.X + _outerGap, l.Y + _outerGap,
+                            l.Width, l.Height, l.State);
+                    }
+                    else
+                    {
+                        return new WindowLocation(l.X + _outerGap + halfInner, l.Y + _outerGap + halfInner,
+                            l.Width - _innerGap, l.Height - _innerGap, l.State);
+                    }
+                }
```
Comment (josteink) [inline src/workspacer.Gap/Layouts/GapLayoutEngine.cs:42]: These calculations are pretty complex. Wouldn't it be nice to add some testes or them? :)

File: src/workspacer.Native/Native/WindowsDeferPosHandle.cs [hunk 3]
```diff
@@ -70,7 +70,9 @@ public void DeferWindowPos(IWindow window, IWindowLocation location)
             int Width = location.Width + offset.Width;
             int Height = location.Height + offset.Height;
 
-            Win32.DeferWindowPos(_info, window.Handle, IntPtr.Zero, X, Y, Width, Height, flags);
+            var oldLocation = window.Location;
+            if (oldLocation.X != X || oldLocation.Y != Y || oldLocation.Width != Width || oldLocation.Height != Height)
+                Win32.DeferWindowPos(_info, window.Handle, IntPtr.Zero, X, Y, Width, Height, flags);
```
Comment (josteink) [inline src/workspacer.Native/Native/WindowsDeferPosHandle.cs:75]: This change looks harmless enough in itself, but I'm wondering why it's needed now.

Is this required to support the other changes in this PR?

File: src/workspacer.Native/Native/WindowsManager.cs [hunk 4]
```diff
@@ -219,6 +219,8 @@ private void WindowHook(IntPtr hWinEventHook, Win32.EVENT_CONSTANTS eventType, I
                     case Win32.EVENT_CONSTANTS.EVENT_OBJECT_LOCATIONCHANGE:
                         WindowMove(hwnd);
                         break;
+                    default:
+                        break;
```
Comment (josteink) [inline src/workspacer.Native/Native/WindowsManager.cs:223]: Any reason this was added?

File: src/workspacer.Shared/Workspace/IWorkspace.cs [hunk 5]
```diff
@@ -128,6 +130,8 @@ public interface IWorkspace
         /// </summary>
         void DoLayout();
 
+        event AfterWorkspaceLayoutDelegate AfterLayout;
```
Comment (josteink) [inline src/workspacer.Shared/Workspace/IWorkspace.cs:133]: Event-names should typically be given a `On`-prefix.

File: src/workspacer/workspacer.csproj [hunk 6]
```diff
@@ -29,10 +29,16 @@
...
     <ProjectReference Include="..\workspacer.Watcher\workspacer.Watcher.csproj" ReferenceOutputAssembly="false" />
+	  <ProjectReference Include="..\workspacer.FocusBorder\workspacer.FocusBorder.csproj" ReferenceOutputAssembly="false" />
   </ItemGroup>
   <Target Name="CopyPluginsAfterBuild" AfterTargets="Build">
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Bar\$(OutDir)workspacer.Bar.dll" DestinationFolder="$(TargetDir)plugins\workspacer.Bar\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Gap\$(OutDir)workspacer.Gap.dll" DestinationFolder="$(TargetDir)plugins\workspacer.Gap\" />
+	<Copy SourceFiles="$(SolutionDir)src\workspacer.FocusBorder\$(OutDir)workspacer.FocusBorder.dll" DestinationFolder="$(TargetDir)plugins\workspacer.FocusBorder\" />
+    <ItemGroup>
+	    <_FSharpConfigCopyItems Include="$(SolutionDir)src\workspacer.FSharpConfig\$(OutDir)*.dll" />
+    </ItemGroup>
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:40]: This change looks unrelated to the rest of the PR.

File: src/workspacer/workspacer.csproj [hunk 7]
```diff
@@ -29,10 +29,16 @@
...
+    <Copy SourceFiles="@(_FSharpConfigCopyItems)" DestinationFolder="$(TargetDir)plugins\workspacer.FSharpConfig\" />
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:41]: These F# bits change looks unrelated to the rest of the PR.

File: src/workspacer/workspacer.csproj [hunk 8]
```diff
@@ -29,10 +29,16 @@
     <ProjectReference Include="..\workspacer.FocusIndicator\workspacer.FocusIndicator.csproj" ReferenceOutputAssembly="false" />
     <ProjectReference Include="..\workspacer.TitleBar\workspacer.TitleBar.csproj" ReferenceOutputAssembly="false" />
     <ProjectReference Include="..\workspacer.Watcher\workspacer.Watcher.csproj" ReferenceOutputAssembly="false" />
+	  <ProjectReference Include="..\workspacer.FocusBorder\workspacer.FocusBorder.csproj" ReferenceOutputAssembly="false" />
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:32]: Weird indentation here with a mixture of tabs and spaces. Keep to spaces only please :)

File: src/workspacer/workspacer.csproj [hunk 9]
```diff
@@ -29,10 +29,16 @@
...
   </ItemGroup>
   <Target Name="CopyPluginsAfterBuild" AfterTargets="Build">
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Bar\$(OutDir)workspacer.Bar.dll" DestinationFolder="$(TargetDir)plugins\workspacer.Bar\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Gap\$(OutDir)workspacer.Gap.dll" DestinationFolder="$(TargetDir)plugins\workspacer.Gap\" />
+	<Copy SourceFiles="$(SolutionDir)src\workspacer.FocusBorder\$(OutDir)workspacer.FocusBorder.dll" DestinationFolder="$(TargetDir)plugins\workspacer.FocusBorder\" />
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:37]: Weird indentation here with a mixture of tabs and spaces. Keep to spaces only please :)

File: src/workspacer/workspacer.csproj [hunk 10]
```diff
@@ -43,11 +49,16 @@
   <Target Name="CopyPluginsAfterPublish" AfterTargets="Publish">
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Bar\$(OutDir)workspacer.Bar.dll" DestinationFolder="$(PublishDir)plugins\workspacer.Bar\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Gap\$(OutDir)workspacer.Gap.dll" DestinationFolder="$(PublishDir)plugins\workspacer.Gap\" />
+	<Copy SourceFiles="$(SolutionDir)src\workspacer.FocusBorder\$(OutDir)workspacer.FocusBorder.dll" DestinationFolder="$(PublishDir)plugins\workspacer.FocusBorder\" />
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:52]: Weird indentation here with a mixture of tabs and spaces. Keep to spaces only please :)

File: src/workspacer/workspacer.csproj [hunk 11]
```diff
@@ -43,11 +49,16 @@
...
     <Copy SourceFiles="$(SolutionDir)src\workspacer.ActionMenu\$(OutDir)workspacer.ActionMenu.dll" DestinationFolder="$(PublishDir)plugins\workspacer.ActionMenu\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.FocusIndicator\$(OutDir)workspacer.FocusIndicator.dll" DestinationFolder="$(PublishDir)plugins\workspacer.FocusIndicator\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.TitleBar\$(OutDir)workspacer.TitleBar.dll" DestinationFolder="$(PublishDir)plugins\workspacer.TitleBar\" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Watcher\$(OutDir)workspacer.Watcher.dll" DestinationFolder="$(PublishDir)" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Watcher\$(OutDir)workspacer.Watcher.exe" DestinationFolder="$(PublishDir)" />
     <Copy SourceFiles="$(SolutionDir)src\workspacer.Watcher\$(OutDir)workspacer.Watcher.pdb" DestinationFolder="$(PublishDir)" />
+    <ItemGroup>
+	    <_FSharpConfigCopyItems Include="$(SolutionDir)src\workspacer.FSharpConfig\$(OutDir)*.dll" />
+    </ItemGroup>
+    <Copy SourceFiles="@(_FSharpConfigCopyItems)" DestinationFolder="$(PublishDir)plugins\workspacer.FSharpConfig\" />
```
Comment (josteink) [inline src/workspacer/workspacer.csproj:62]: These F# bits also look unrelated to the rest of the PR.

File: src/workspacer.FocusIndicator/FocusIndicatorPlugin.cs [hunk 12]
```diff
@@ -7,8 +7,6 @@ public class FocusIndicatorPlugin : IPlugin
 
         private FocusIndicatorForm _form;
 
-        public FocusIndicatorPlugin() : this(new FocusIndicatorPluginConfig()) { }
-
```
Comment (josteink) [inline src/workspacer.FocusIndicator/FocusIndicatorPlugin.cs:11]: Any reason to remove this constructor? Someone might be depending on it.

File: src/workspacer.Bar/BarPluginConfig.cs (hunk 1 above)
Comment (tlsomers) [reply src/workspacer.Bar/BarPluginConfig.cs]: Mainly due to being unused, as `DefaultWidgetBackground` is the property used for the form background at the moment.

File: src/workspacer.Gap/Layouts/GapLayoutEngine.cs (hunk 2 above)
Comment (tlsomers) [reply src/workspacer.Gap/Layouts/GapLayoutEngine.cs]: As this is unrelated to this pull request (sorry, I was mostly working on modding for myself before thinking it would be good to contribute), I have removed the gap changes from this pr.

File: src/workspacer.Native/Native/WindowsDeferPosHandle.cs (hunk 3 above)
Comment (tlsomers) [reply src/workspacer.Native/Native/WindowsDeferPosHandle.cs:75]: Working with Rider, I found that the window would refresh (fully grey for half a second or so) upon forcing a layout. This prevents unnecessary movement, thus resolving the issue.

File: src/workspacer.Shared/Workspace/IWorkspace.cs (hunk 5 above)
Comment (tlsomers) [reply src/workspacer.Shared/Workspace/IWorkspace.cs]: `OnLayoutCompleted` sounds good to me, so it has been changed accordingly.

File: src/workspacer.FocusIndicator/FocusIndicatorPlugin.cs (hunk 12 above)
Comment (tlsomers) [reply src/workspacer.FocusIndicator/FocusIndicatorPlugin.cs]: No reason other than it not being used internally, and that the config extensions would usually be used for the configuration over the constructor. It has been added back in.

File: src/workspacer.Bar/BarPluginConfig.cs (hunk 1 above)
Comment (josteink) [reply src/workspacer.Bar/BarPluginConfig.cs]: Fair enough. Then we keep it.

File: src/workspacer.Native/Native/WindowsDeferPosHandle.cs (hunk 3 above)
Comment (josteink) [reply src/workspacer.Native/Native/WindowsDeferPosHandle.cs:75]: Sounds good. Could have been it's own PR even. But lets keep it here then :)

File: src/workspacer.Shared/Workspace/IWorkspace.cs (hunk 5 above)
Comment (josteink) [reply src/workspacer.Shared/Workspace/IWorkspace.cs]: Not seeing the change here though. Have you remembered to push? :smile:

File: src/workspacer.Gap/Layouts/GapLayoutEngine.cs (hunk 2 above)
Comment (josteink) [reply src/workspacer.Gap/Layouts/GapLayoutEngine.cs]: Great. That makes it easier to review the remaining code!

File: src/workspacer.Shared/Workspace/IWorkspace.cs (hunk 5 above)
Comment (tlsomers) [reply src/workspacer.Shared/Workspace/IWorkspace.cs]: I used a force push to make sure that non-pr code doesn't interfere with future branches that make those changes, so it doesn't detect the change :). If you look at the changes it's definitely `OnLayoutCompleted` now

**Review by josteink — APPROVED** [review]

**Comment by josteink** [comment]
LGTM. Merged!

**Comment by pranavpa8788** [comment]
I get this error: 

Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (19,18): error CS0234: The type or namespace name 'FocusBorder' does not exist in the namespace 'workspacer' (are you missing an assembly reference?)

when I use 

`using workspacer.FocusBorder;`

I am running Windows 11 and installed workspacer using scoop

**Comment by dalyIsaac** [comment]
You're likely missing a `#r "C:\...\workspacer.FocusBorder.dll` at the top of your csx file.

**Comment by pranavpa8788** [comment]
But I don't have such a dll file though. My plugins directory looks like 
image

**Comment by dalyIsaac** [comment]
> workspacer (0.9.11)

You'll need to download an unstable version (`0.9.12.x`)

**Comment by pranavpa8788** [comment]
I see...is there any other alternative? Like can I manually compile the dll files from the source files?

**Comment by dalyIsaac** [comment]
Yes, you could compile it. Alternatively, you could download the specific dll from the release `.zip` and place it in the appropriate location (https://github.com/workspacer/workspacer/releases/tag/unstable).

However, there aren't any guarantees that it'll work with 0.9.11.

**Comment by pranavpa8788** [comment]
Thanks! I downloaded the unstable release and used that plugin dll and now i am able to import it without any error. Working on figuring out how to actually use it haha 😅
